import React from "react";
import Homecontent from "@/components/HomeContent/HomeContent";
import Head from "next/head";
const connect = () => {
	return (
		<div>
			{" "}
			<Head>
				{" "}
				<title>Connect</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<meta name="author" content="Thanh Minh" />
			</Head>
			<Homecontent
				heading={"Connect"}
				message={"Connect to business to become more socialization"}
				backgroundimg={"default-img3"}
			/>
		</div>
	);
};

export default connect;
