import Attraction from "@/components/Attraction/Attraction";
import Homecontent from "@/components/HomeContent/HomeContent";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<div>
				<Head>
					{" "}
					<title>Home</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<meta name="author" content="Thanh Minh" />
				</Head>

				<Homecontent
					heading={"Home Page"}
					message={"Head to digital solutions for Vung Tau"}
					backgroundimg={"default-img1"}
				/>
				<Attraction />
			</div>
		</>
	);
}
