import React from "react";
import Head from "next/head";
import Homecontent from "@/components/HomeContent/HomeContent";
import Gallery from "@/components/Gallery/Gallery";
const scenes = ({ results1, results2 }) => {
	return (
		<div>
			{" "}
			<Head>
				{" "}
				<title>Scenes</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<meta name="author" content="Thanh Minh" />
			</Head>
			<Homecontent
				heading={"Scenes"}
				message={"Protect scenes from pollution"}
				backgroundimg={"default-img"}
			/>
			<Gallery data1={results1} data2={results2} />{" "}
		</div>
	);
};
export default scenes;
export async function getStaticProps() {
	// const { events_categories } = await import("./data/sample.json");
	const { vung_tau_before, vung_tau_after } = await import("./data/data.json");
	return {
		props: {
			results1: vung_tau_before,
			results2: vung_tau_after,
		},
	};
}
